package com.demo.model;

public enum Category {
    APPLICATION_DEVELOPMENT, ADMINISTRATION, ANALYSING_AND_MANAGEMENT,NETWORK_SYSTEMS,
    MEDIA_AND_COMMUNICATION, DIGITAL_MARKETING,GRAPHIC_DESIGNING, COMPUTER_OPERATING_AND_HARDWARE
}
